### ISSUE TITLE
command line tool reports wrong input numbers

### ISSUE THREAD

**Issue by a16bitsysop** [SequentMicrosystems/16inpind-rpi#1]
with inputs connected from 1-8 the node red module reads channels 1-8 correctly, but the command line tool reports inputs 9-16

**Comment by alexburcea2877** [comment]
Give me some time to check on get back to you.
Thank you.

**Comment by alexburcea2877** [comment]
Can you tell me the card hardware version? I tested on v1.0 and all looks ok.

**Comment by a16bitsysop** [comment]
I will check, also I have an 8 mosfet card (id 1 with 16 input id 2) and if I  do`8mosind -list` i get `2 board(s) detected Id: 1 2` but `16inpind -list` gives `1 board(s) detected Id: 2`

**Comment by alexburcea2877** [comment]
Yes, because 8-mosfet cards was made with 2 type of IOExpanders (chip shortage reasons) and one of them have the same i2c address scheme as the 16-inputs card. So the 8mosind -list gives you false response because it search for both types of IOExpanders.

**Comment by a16bitsysop** [comment]
on the card it says v3.1, its the one with the modbus and 5v on the side

**Comment by alexburcea2877** [comment]
Hi,

Sorry for the delayed answer. I di not have that version of card but testing with an older version, The NodeRED "noder-red-contrib-sm-16inpind" and  "16inpind" command gives the same response. Please check again maybe you access the 8mosfets card with one of the methods.
I asked for a sample card V3.1 from our office in CA but this will take a little, until then please retest the issue.

**Comment by a16bitsysop** [comment]
okay, `8mosind 2 read [1-8]` which is ID of 16inpind returns all zeros, with an input active on channel 7.
`16inpind 2 rd 7` returns `0`, but `16inpind 2 rd 15` returns `1` (with only input 7 active).

using the 8mosind node-red module, triggered by an inject node trying to set channel 7 gives the error: `Error: , Remote I/O error`. It doesn't look like the 8mosind node red module can read the state of a channel.

**Comment by alexburcea2877** [comment]
You have right, the 8mosind will not read 16inputs card but you can get false readings with _16inpind_  accessing the 8-mos card. You must use different stack level for the cards and access each card with the right software.
Is strange because the NodeRed and command line give me the same results even if I have old version card.
I will test again when I receive the v3.1 card.

**Comment by a16bitsysop** [comment]
yes they have different ID's, I have an ID problem with an industrial automation card actually.  If no jumpers are on, or jumpers are not set to 7 the card will change to ID 7 after a short time.  If the jumpers are set to 7 the ID stays at 7?

**Comment by alexburcea2877** [comment]
For the industrial card, please place all the ID jumpers and go to the update folder and run ./update 7 command.
Let me know if after the update you have the same problem.

**Comment by a16bitsysop** [comment]
okay, will try that.

**Comment by alexburcea2877** [comment]
Are you sure that you have 16-inputs v3.1? We currently sell V1.0.
Can you send me a picture with the card.

**Comment by a16bitsysop** [comment]
![IMG_20221228_201050736](https://user-images.githubusercontent.com/32509178/209867251-c4c7cc76-4e40-488c-9903-7f0674b537a7.jpg)

**Comment by alexburcea2877** [comment]
Ok, 
I was completely forgot about our first series of 16-inputs card which works with a different software  on a different repository: https://github.com/SequentMicrosystems/16inputs-rpi
Sorry for this, I did not imagine there is someone that bought this card and never use it until now.

**Comment by a16bitsysop** [comment]
thanks will try that

**Comment by a16bitsysop** [comment]
yes that works! `16inputs 2 rd 7` returns 1 and `16inputs 2 rd 15` returns 0

I had actually used the correct node red module for the old card, so must have chosen wrong repo for command line!
