### ISSUE TITLE
Understanding how to use the board with Python

### ISSUE THREAD

**Issue by jacklythgoee** [SequentMicrosystems/16inpind-rpi#3]
Hi.
I have bought the device from PiHut, where i have installed the libraries.
I am trying to run a program that can use 16 inputs from a 12v signal. Send them to the I2C and then add a case switch statement to be able to identify which button has been pressed.

How can i implement this? I see two commands, one that i think i need to use which is the readCh, am i stupid because this aint working. Positive side of a battery to input and negative to ground. Should send a signal other than 0

**Comment by alexburcea2877** [comment]
Hi,
Positive terminal to input and negative to the COM pin (the pin in the midle of the input connector). The GND of the card is isolated to the inputs.
The readCh should work.
Is better if you install and use for testing the 16inpind command , instructions [here](https://github.com/SequentMicrosystems/16inpind-rpi/blob/main/README.md).

**Comment by jacklythgoee** [comment]
Hi,
I hooked the positive terminal to "IN3" and the negative terminal to "3-4COM". I ran this code
`while True:
              print(lib16in.readCh(0,3))
               time.sleep(1)`

This code will just print 0 even when connected to a 9v battery. I did try without the print statement and just the function, but did not return anything.

**Comment by alexburcea2877** [comment]
Replace readCh(0,3) with readAll(0). You should get all channels as 16 bit number.

**Comment by jacklythgoee** [comment]
Yeah i have managed to get some code that shows the individual pins that are high. But the readCh() function does not work. It will print 0 constantly, signal or not.

**Comment by alexburcea2877** [comment]
I will check it out in a few days when I get home and let you know.

Alex

**Comment by jacklythgoee** [comment]
"def handle_pin1_press():
    print("PIN 1 - GREEN")

def handle_pin2_press():
    print("PIN 2 - RED")

def display_pressed_pins():
    previous_input_values = lib16in.readAll(0)  # Read the initial values from all the inputs
    while True:
        input_values = lib16in.readAll(0)  # Read the current values from all the inputs
        for pin_num in range(16):
            pin_value = 2 ** (pin_num + 8)  # Calculate the value corresponding to the pin
            if input_values & pin_value and not previous_input_values & pin_value:
                if pin_num == 0:
                    handle_pin1_press()
                elif pin_num == 1:
                    handle_pin2_press()
        previous_input_values = input_values  # Update the previous input values
        time.sleep(0.1)

# Call the function to start displaying the pressed pins
display_pressed_pins()"


This does work and shows from pin1 to 8. Havent got it to work on the other side of the board as thats 1-128

**Comment by jacklythgoee** [comment]
No worries now, i just reinstalled the library using the whole file instead of git. Seemed to work after that.

**Comment by alexburcea2877** [comment]
Since you solve the problem I will close this Issue.
