### ISSUE TITLE
Stacking Boards

### ISSUE THREAD

**Issue by jacklythgoee** [SequentMicrosystems/16inpind-rpi#4]
Hi,
I have just purchased a second board, plugged it in the top, but the code i created didnt seem to work.

I went into the terminal and used 16pind 0 rd, where it would return the correct number
I then tried 16pind 1 rd, and it returns Fail to read.

I can see that the second board is powered, but unsure how to resolve this issue

**Comment by jacklythgoee** [comment]
Ignore me, im just being silly

**Comment by alexburcea2877** [comment]
No problem, it was quicker that my typing.

**Comment by jacklythgoee** [comment]
However on PIHut, they have got the stack multiple cards diagram wrong compared to the one on the sequence website. Thats what messed me up.

**Comment by alexburcea2877** [comment]
Thanks, I will check that. There is a command "16inpind -list" which tells you how many cards are connected and their stack level settings.

**Comment by jacklythgoee** [comment]
Yeah my issue was just not having the jumper on the board that's why I was getting the errors.
